name: sync-single-to-azure

on: 
  workflow_dispatch

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      # - uses: actions/checkout@v5.0.0
      #   with:
      #     fetch-depth: 0 # <-- clone with complete history
      #     ref: main
      #     repository: 'dirkarnez/${{ secrets.repository }}'
      #     path: '${{ secrets.repository }}'
      #     submodules: 'recursive'
      - shell: cmd
        env:
          REPOSITORY: ${{ secrets.REPOSITORY }}
          TESTING: toJSON(${{ secrets.REPOSITORY }})
        run: |
          echo $TESTING
          git clone https://dirkarnez:${{ secrets.GH_PAT }}@github.com/dirkarnez/%REPOSITORY%.git
            
    # Powershell:  [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes("dirkarnez:MY_PAT"))
      - continue-on-error: true
        shell: bash
        run: |
          result="$(echo -n "dirkarnez:${{ secrets.AZURE_PAT }}" | base64 | tr -d '\n')" && \
          curl -X POST "https://dev.azure.com/dirkarnez/My%20GitHub%20backup/_apis/git/repositories?api-version=7.1" \
          -H 'Content-Type: application/json' \
          -H "Authorization: Basic $result"  \
          -d '{"name":"${{ secrets.repository }}"}' && \
          ls

      - shell: bash
        run: | 
          cd ${{ secrets.repository }} && \
          git config --global user.name "dirkarnez" && \
          git config --global user.email "smalldirkalex@gmail.com" && \
          git remote add azure 'https://dirkarnez:${{ secrets.AZURE_PAT }}@dev.azure.com/dirkarnez/My%20GitHub%20backup/_git/${{ secrets.repository }}' && \
          git push -u azure main
          
      # - uses: yesolutions/mirror-action@v0.7.0
      #   with:
      #       REMOTE: ssh://git@bitbucket.org/dirkarnez/${{ github.event.repository.name }}.git
      #       GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
      #       GIT_SSH_NO_VERIFY_HOST: "true"

      # https://github.com/dirkarnez/internal-git-notes/blob/master/Bitbucket/azure/private-openssh-format
      # - uses: yesolutions/mirror-action@v0.7.0
      #   with:
      #       REMOTE: git@ssh.dev.azure.com:v3/dirkarnez/My%20GitHub%20backup/${{ github.event.repository.name }}
      #       GIT_SSH_PRIVATE_KEY: ${{ secrets.AZURE_REPO_SSH_PRIVATE_KEY }}
      #       GIT_SSH_NO_VERIFY_HOST: "true"
